name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '27 13 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-24.04
    steps:
      - name: Check out this repo
        uses: actions/checkout@v4
      - name: Fetch Google CT Log List
        run: curl -sSL 'https://www.gstatic.com/ct/log_list/v3/all_logs_list.json' | jq . > data/google/all_log_list.json
      - name: Fetch Apple CT Log List
        run: curl -sSL 'https://valid.apple.com/ct/log_list/current_log_list.json' | jq . > data/apple/current_log_list.json
      - name: Commit and push if it changed
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push
